'use strict';
(() => {
  const $ = (s, root = document) => root.querySelector(s);
  const escape = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const list = (items) => `<ul class="compact-list">${items.map(x => `<li>${escape(x)}</li>`).join('')}</ul>`;
  const titles = {overview:'项目概览',map:'学习版图',research:'当前研究',evidence:'实验与证据',resources:'精选资料',updates:'更新与维护'};
  const groupNames = {foundation:'基础主线',linked:'配套能力',conditional:'按目标展开'};
  const main = $('#main');
  const storeKey = 'ai-engineering-u01-draft-v1';
  let data, mapFilter = 'all', resourceFilter = 'all', toastTimer, saveTimer;
  function toast(text) { $('#toast').textContent = text; $('#toast').classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => $('#toast').classList.remove('show'), 2800); }
  function download(name, text, type = 'text/plain;charset=utf-8') { const url = URL.createObjectURL(new Blob([text], {type})); const a = document.createElement('a'); a.href=url; a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(url), 1000); }
  async function copy(text) { try { await navigator.clipboard.writeText(text); toast('已复制项目续接说明'); } catch { download('继续项目.txt', text); toast('无法访问剪贴板，已导出说明'); } }
  function tag(text, kind = '') { return `<span class="pill ${kind}">${escape(text)}</span>`; }
  function intro(eyebrow, title, text) { return `<section class="intro"><div class="eyebrow">${eyebrow}</div><h1>${escape(title)}</h1><p>${escape(text)}</p></section>`; }
  function domainCard(d, expanded=false) { return `<article class="card domain-card"><div class="card-meta"><span class="card-number">${d.number} / ${groupNames[d.group]}</span>${tag(d.priority,d.group==='foundation'?'':'neutral')}</div><h3>${escape(d.title)}</h3><div class="en">${escape(d.en)}</div><p>${escape(d.short)}</p>${expanded?`<p class="mini"><strong>为什么投入：</strong>${escape(d.why)}</p>`:''}<button class="text-link" data-domain="${d.id}">查看依据与掌握标准 <span aria-hidden="true">↗</span></button></article>`; }
  function overview() { return `<section class="intro"><div class="intro-row"><div><div class="eyebrow">A PERSONAL ENGINEERING PRACTICE</div><h1>AI Engineering 能力建设</h1></div>${tag('框架已修订 · 个人掌握待校准','warm')}</div><p>${escape(data.goal)}</p></section><section class="hero"><div><div class="eyebrow">THE GOAL IS CAPABILITY, NOT OUTPUT</div><h2>${escape(data.subtitle)}</h2><p>理解系统为什么这样工作，知道应该改变哪里，<br>并用证据判断改变是否有效。</p></div><div class="hero-side"><small>三条基础主线相互连接，<br>不再套用固定四阶段。</small><a class="btn" href="#map">查看学习版图 <span aria-hidden="true">↗</span></a></div></section><div class="section-heading"><h2>当前优先补齐什么</h2><p>已明确的缺口 + 前置价值</p></div><div class="grid3">${data.domains.filter(d=>d.group==='foundation').map(d=>domainCard(d)).join('')}</div><div class="split"><section class="card next-card"><div class="card-meta"><span class="eyebrow">NEXT / 建议入口</span>${tag('尚未运行','warm')}</div><h3>${escape(data.current.title)}</h3><p>${escape(data.current.question)}</p><a class="text-link" href="#research">展开当前问题与实验设计 <span aria-hidden="true">→</span></a><p class="muted-note" style="margin-top:16px;margin-bottom:0">L01 是可跳过的参考，不是强制起点。</p></section><section class="card"><div class="note-list">${data.principles.map((p,i)=>`<div class="note-row"><span class="small-number">0${i+1}</span><div><strong>${escape(p.title)}</strong><p>${escape(p.text)}</p></div></div>`).join('')}</div></section></div><p class="muted-note">当前状态：${escape(data.state)}</p>`; }
  function mapPage() { return `${intro('LEARNING LANDSCAPE','为什么学这些，而不是别的？','按限制当前判断的程度、跨任务复用性和前置价值安排投入。模型适配是综合应用，工作迁移是验收方式，不单独充当最高层级的课程。')}<div class="filterbar" aria-label="能力分类">${[['all','全部领域'],['foundation','基础主线'],['linked','配套能力'],['conditional','按目标展开']].map(([id,label])=>`<button class="chip" data-map-filter="${id}" aria-pressed="${mapFilter===id}">${label}</button>`).join('')}</div><div class="map-grid">${data.domains.filter(d=>mapFilter==='all'||d.group===mapFilter).map(d=>domainCard(d,true)).join('')}</div><div class="callout">${escape(data.priority_note)}</div>`; }
  function research() { const c=data.current; return `${intro('CURRENT INQUIRY','从一次有辨别力的比较开始',c.why)}<div class="research-grid"><article class="study-block"><div class="study-title"><div class="card-meta"><span class="eyebrow">${c.id} / APPLICATION CANDIDATE</span>${tag('尚未运行','warm')}</div><h2>${escape(c.question)}</h2><p>当前以实验设计为建议入口；更重要的真实问题出现时，可以替换载体，不重新改变项目目标。</p></div>${[['比较对象',c.baseline],['观察与判分',c.observe],['分析与样本',c.analysis],['用于定位的干预',c.intervention],['个人需要留下的判断',c.personal]].map(([title,text])=>`<section class="study-section"><h3>${title}</h3><p>${escape(text)}</p></section>`).join('')}</article><div class="side-stack"><section class="card next-card"><span class="eyebrow">NEXT ACTION</span><h3 style="margin-top:10px">先写清准备改变哪个决定</h3><p>${escape(c.next)}</p><div class="callout" style="margin-bottom:0">不预设改造有收益；有依据的 no-op 也是有效结果。</div></section><section class="card"><h3>这一轮应留下</h3>${list(c.outcomes)}<p class="muted-note">${escape(c.lesson)}</p><a class="history-link" href="lesson-01.md" download>读取 L01 参考材料 ↓</a></section><section class="card draft-card"><div class="card-meta"><h3>记录自己的关键判断</h3>${tag('本地草稿','neutral')}</div><p>先记录预测与实验取舍，再看解释和结果。草稿不会自动成为掌握证据。</p><label class="form-label" for="draft-decision">准备支持哪个决定？</label><textarea id="draft-decision" data-draft="decision" placeholder="例如：是否把某类规范改为按需读取；不能以字数减少直接判成功。"></textarea><label class="form-label" for="draft-prediction">你的预测与替代解释</label><textarea id="draft-prediction" data-draft="prediction" placeholder="哪些结果符合预期？哪些现象可能来自加载、内容或模型本身？"></textarea><label class="form-label" for="draft-evidence">什么证据会改变你的判断？</label><textarea id="draft-evidence" data-draft="evidence" placeholder="写清判据、观察边界与下一步检查。"></textarea><div class="button-row"><button class="btn small" id="export-draft">导出判断记录 ↓</button><button class="btn secondary small" id="clear-draft">清空草稿</button></div><div id="save-status" class="save-status">只保存到当前浏览器，不会写入网站或正式进度。</div></section></div></div>`; }
  function evidencePage() { return `${intro('EVIDENCE REGISTER','把材料、运行和掌握分开','只记录实际存在的证据。没有能力雷达评分，没有用阅读数量推算的完成百分比。')}${data.evidence.map(e=>`<article class="card evidence-card"><div class="eyebrow" style="margin-bottom:12px">${e.id} / ${escape(e.kind)}</div><div class="evidence-top"><h3>${escape(e.title)}</h3>${tag(e.status,e.status==='尚未开展'?'warm':'neutral')}</div><p><b>当前可支持：</b>${escape(e.supports)}</p><p><b>结论边界：</b>${escape(e.limit)}</p></article>`).join('')}<div class="callout">每项个人能力只记录：现在能独立做什么、依据是什么、下一步具体缺什么。新的运行数据应带任务、版本、配置、判分与失败记录；不能以最终报告代替原始证据。</div><div class="section-heading"><h2>留下证据之后，更新什么</h2></div><div class="grid3">${[['当前理解','写明哪一个预测成立或被推翻；不是重写一篇泛化总结。'],['机制判断','指出定位到了哪一段；没有观察到的中间过程保持未知。'],['下一步投入','决定继续、修改、换方向或停止。不要因为教材已写好就强制按顺序推进。']].map(([a,b])=>`<section class="card"><h3 style="font-size:16px;margin-bottom:10px">${a}</h3><p style="font-size:13px;color:var(--muted)">${b}</p></section>`).join('')}</div>`; }
  function resourceCard(r) { return `<article class="card resource-card"><div class="eyebrow">${escape(r.publisher)}</div><h3>${escape(r.title)}</h3><p>${escape(r.purpose)}</p><p class="use"><b>读后要做：</b>${escape(r.use)}</p><a class="text-link" href="${escape(r.url)}" target="_blank" rel="noopener noreferrer">打开原始资料 ↗</a></article>`; }
  function resourcesPage() { return `${intro('REFERENCE SHELF','少量主材料，明确使用目的','文章用于理解与发现机制；当前实现和实际收益仍需源码、轨迹与实验。X 与社区提供线索，不替代有效性判断。')}<div class="filterbar" aria-label="资料分类">${[['all','全部资料'],['evaluation','评估与统计'],['runtime','运行与状态'],['model','模型与数据'],['tools','工具'],['human','人机理解']].map(([id,title])=>`<button class="chip" data-resource-filter="${id}" aria-pressed="${resourceFilter===id}">${title}</button>`).join('')}</div><p class="source-note">资料入口沿用已有项目材料；版本敏感的接口与行为，在实际实验时重新核对。这里不以“已阅读”标记个人掌握。</p><div class="grid2">${data.resources.filter(r=>resourceFilter==='all'||r.domain===resourceFilter).map(resourceCard).join('')}</div>`; }
  function updatesPage() { return `${intro('PROJECT CONTINUITY','同一个项目，持续修订','网站不是一次性报告。目标、优先级、当前单元和证据共用同一份可版本化内容；页面只是它的展示。')}<div class="timeline">${data.changes.map(c=>`<article class="timeline-item"><time>${c.date} · v${c.version}</time><h3>${escape(c.title)}</h3><p>${escape(c.detail)}</p></article>`).join('')}</div><div class="maintenance-grid"><section class="card"><h3>唯一内容源</h3><div class="codeblock">ai-engineering/\n  project.json   ← 目标、优先级与状态\n  lesson-01.md   ← 可选教学材料\n  index.html    ← 页面结构\n  app.js        ← 展示与导出\n  styles.css    ← 样式\n  README.md     ← 维护与部署说明</div><p>${escape(data.maintenance.truth)}</p><p>${escape(data.maintenance.update)}</p><div class="button-row"><a class="btn small" href="https://github.com/feng-y/guide-page/edit/main/ai-engineering/project.json" target="_blank" rel="noopener noreferrer">编辑项目内容 ↗</a><button class="btn secondary small" id="export-project">导出内容 JSON ↓</button></div></section><section class="card"><h3>下次怎样接着做</h3><p>在本对话继续，或在新会话中提供项目地址。先恢复最新内容，再做判断与实验，不重新套一个学习框架。</p><div class="codeblock">${escape(data.maintenance.resume)}</div><div class="button-row"><button class="btn small" id="copy-resume">复制续接说明</button><button class="btn secondary small" id="export-taskbook">导出 Taskbook ↓</button></div><p>导出的 Markdown 与 Library 文件是指定版本的快照，不另行维护进度。练习草稿保存在浏览器，不会静默同步或公开。</p></section></div><div class="callout">本项目不覆盖任何业务仓库的规则、源码或实验事实。进入真实实验时，以当时核对的版本和运行证据为准。</div>`; }
  const renderers={overview,map:mapPage,research,evidence:evidencePage,resources:resourcesPage,updates:updatesPage};
  function route() { if(!data)return; if(document.querySelector('[data-draft]')){clearTimeout(saveTimer);saveDraft();} const view=location.hash.slice(1).split('/')[0]||'overview'; const actual=titles[view]?view:'overview'; $('#view-title').textContent=titles[actual]; document.title=`${titles[actual]} · AI Engineering`; document.querySelectorAll('#nav a').forEach(a=>a.dataset.view===actual?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current')); main.innerHTML=renderers[actual](); if(actual==='research')restoreDraft(); window.scrollTo({top:0,behavior:'instant'}); }
  function showDomain(id) { const d=data.domains.find(x=>x.id===id); if(!d)return; const sections=[['为什么现在学',d.why],['学会后能改变的决定',d.decision],['需要掌握的机制',list(d.topics),true],['用这些问题检查理解',list(d.questions),true],['掌握标准',d.mastery],['当前依据与未知',d.evidence],['什么情况下调整优先级',d.revisit]]; $('#detail-content').innerHTML=`<article class="domain-detail">${tag(d.priority)}<h2 id="detail-title">${escape(d.title)}</h2><p class="sub">${escape(d.short)}</p>${sections.map(([t,x,html])=>`<section class="detail-block"><h3>${t}</h3>${html?x:`<p>${escape(x)}</p>`}</section>`).join('')}${d.resources.length?`<section class="detail-block"><h3>对应资料</h3><div class="resource-links">${d.resources.map(id=>data.resources.find(r=>r.id===id)).filter(Boolean).map(r=>`<a href="${escape(r.url)}" target="_blank" rel="noopener noreferrer">${escape(r.publisher)} · ${escape(r.title)} ↗</a>`).join('')}</div></section>`:''}</article>`; $('#detail-dialog').showModal(); $('#detail-dialog').scrollTop=0; }
  function draftValues() { const result={project:data.title,unit:data.current.id,projectVersion:data.version,updatedAt:new Date().toISOString(),status:'本地练习草稿，未经核对，不是正式进度'}; document.querySelectorAll('[data-draft]').forEach(el=>result[el.dataset.draft]=el.value); return result; }
  function restoreDraft(){try{const raw=localStorage.getItem(storeKey);if(raw){const v=JSON.parse(raw);document.querySelectorAll('[data-draft]').forEach(el=>el.value=typeof v[el.dataset.draft]==='string'?v[el.dataset.draft]:'');$('#save-status').textContent='已恢复此浏览器中的草稿；未写入正式进度。';}}catch{$('#save-status').textContent='浏览器存储不可用；可使用导出保存本次记录。';}}
  function saveDraft(){try{localStorage.setItem(storeKey,JSON.stringify(draftValues()));$('#save-status').textContent='已保存到此浏览器；未写入网站或正式进度。';}catch{$('#save-status').textContent='浏览器存储不可用，请导出记录。';}}
  function taskbook(){const d=data;return `# ${d.title}\n\n版本：v${d.version} · 更新：${d.updated}\n\n> 此文件由 project.json 导出。维护源：${d.canonical}\n> 这是版本快照，不独立维护项目进度。\n\n## 目标\n\n${d.goal}\n\n${d.scope}\n\n## 当前状态\n\n${d.state}\n\n## 优先级依据\n\n${d.principles.map(p=>`### ${p.title}\n\n${p.text}`).join('\n\n')}\n\n${d.priority_note}\n\n## 学习版图\n\n${d.domains.map(x=>`### ${x.title} · ${x.priority}\n\n当前依据：${x.evidence}\n\n为什么学：${x.why}\n\n要支持的决定：${x.decision}\n\n${x.topics.map(t=>'- '+t).join('\n')}\n\n掌握标准：${x.mastery}\n\n重排条件：${x.revisit}`).join('\n\n')}\n\n## 当前建议入口：${d.current.id} ${d.current.title}\n\n状态：${d.current.status}\n\n${d.current.question}\n\n${d.current.why}\n\n比较：${d.current.baseline}\n\n观测：${d.current.observe}\n\n分析：${d.current.analysis}\n\n干预：${d.current.intervention}\n\n个人判断：${d.current.personal}\n\n下一步：${d.current.next}\n\n${d.current.lesson}\n\n## 证据目录\n\n${d.evidence.map(e=>`### ${e.id} ${e.title} · ${e.status}\n\n${e.supports}\n\n边界：${e.limit}`).join('\n\n')}\n\n## 资料\n\n${d.resources.map(r=>`- [${r.publisher} · ${r.title}](${r.url})：${r.purpose} 读后动作：${r.use}`).join('\n')}\n\n## 更新记录\n\n${d.changes.map(c=>`### ${c.date} · v${c.version} ${c.title}\n\n${c.detail}`).join('\n\n')}\n\n## 恢复与维护\n\n${d.maintenance.truth}\n\n${d.maintenance.update}\n\n${d.maintenance.resume}\n`;}
  function search(q){const term=q.trim().toLowerCase();const out=$('#search-results');if(!term){out.innerHTML='<p class="muted-note">搜索学习领域、当前问题和参考资料。</p>';return;}const hits=[];data.domains.forEach(d=>{if(JSON.stringify(d).toLowerCase().includes(term))hits.push({title:d.title,text:d.short,domain:d.id});});data.resources.forEach(r=>{if(JSON.stringify(r).toLowerCase().includes(term))hits.push({title:r.title,text:r.publisher+' · '+r.purpose,url:r.url});});if(JSON.stringify(data.current).toLowerCase().includes(term))hits.push({title:'当前研究 · '+data.current.title,text:data.current.question,view:'research'});out.innerHTML=hits.length?hits.slice(0,20).map(h=>h.url?`<a class="search-result" href="${escape(h.url)}" target="_blank" rel="noopener noreferrer"><strong>${escape(h.title)} ↗</strong><small>${escape(h.text)}</small></a>`:`<button class="search-result" ${h.domain?`data-search-domain="${h.domain}"`:`data-search-view="${h.view}"`}><strong>${escape(h.title)}</strong><small>${escape(h.text)}</small></button>`).join(''):'<p class="empty">没有匹配内容，试试“状态”或“判分”。</p>';}
  document.addEventListener('click',event=>{const el=event.target.closest('button,a');if(!el||!data)return;if(el.matches('.close-dialog'))el.closest('dialog').close();if(el.dataset.domain)showDomain(el.dataset.domain);if(el.dataset.mapFilter){mapFilter=el.dataset.mapFilter;route();}if(el.dataset.resourceFilter){resourceFilter=el.dataset.resourceFilter;route();}if(el.dataset.searchDomain){$('#search-dialog').close();showDomain(el.dataset.searchDomain);}if(el.dataset.searchView){$('#search-dialog').close();location.hash=el.dataset.searchView;}if(el.id==='search-open'){$('#search-dialog').showModal();$('#search-input').value='';search('');$('#search-input').focus();}if(el.id==='export-draft'){saveDraft();const v=draftValues();download(`AI-Engineering-${data.current.id}-判断记录.md`,`# ${data.current.id} · 个人判断草稿\n\n时间：${v.updatedAt}\n项目版本：${v.projectVersion}\n状态：${v.status}\n\n## 准备支持的决定\n\n${v.decision}\n\n## 预测与替代解释\n\n${v.prediction}\n\n## 什么证据会改变判断\n\n${v.evidence}\n`,'text/markdown;charset=utf-8');}if(el.id==='clear-draft'){if(confirm('清空当前浏览器中的三项草稿？不会影响正式项目内容。')){try{localStorage.removeItem(storeKey);}catch{}document.querySelectorAll('[data-draft]').forEach(x=>x.value='');$('#save-status').textContent='草稿已清空；正式项目内容未改变。';}}if(el.id==='export-project')download(`AI-Engineering-project-v${data.version}.json`,JSON.stringify(data,null,2),'application/json');if(el.id==='export-taskbook')download('AI-Engineering-Taskbook.md',taskbook(),'text/markdown;charset=utf-8');if(el.id==='copy-resume')copy(data.maintenance.resume+'\n\n'+data.canonical);});
  document.addEventListener('input',event=>{if(event.target.matches('[data-draft]')){clearTimeout(saveTimer);saveDraft();}if(event.target.id==='search-input')search(event.target.value);});
  document.addEventListener('keydown',event=>{if(event.key==='/'&&!event.ctrlKey&&!event.metaKey&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!document.querySelector('dialog[open]')){event.preventDefault();$('#search-open').click();}});
  document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}}));
  window.addEventListener('hashchange',route);
  window.addEventListener('pagehide',()=>{if(data&&document.querySelector('[data-draft]'))saveDraft();});
  fetch('project.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}).then(p=>{if(!p.version||!Array.isArray(p.domains)||!p.current)throw new Error('项目数据结构不完整');data=p;$('#version').textContent=`v${p.version}`;$('#footer-meta').textContent=`更新 ${p.updated} · 内容以 project.json 为准`;route();}).catch(error=>{main.innerHTML=`<section class="card"><h1 style="font-size:26px">项目内容暂未加载</h1><p style="margin:18px 0">请刷新页面，或通过本地 HTTP 服务打开完整站点目录。</p><p><code>python3 -m http.server 8000</code></p><p class="muted-note">${escape(error.message)}</p><a class="text-link" href="project.json">直接读取项目内容 →</a></section>`;$('#version').textContent='加载失败';});
})();
